export const responses = [
    "Yes",
    "please wait 2-3 business days for respond",
    "five or somethin",
    "Is that all?",
    "K.",
    "maths is hard.",
    "22. I am simply the vessel for this number.",
    "We may never know the truth",
    "Does this number truly exist, or is it merely a concept?",
    "Ask the person next to you.",
    "Send help",
    "Insert coin to continue.",
    "Seven. Can I go home now?",
    "the answer is in page 39",
    "I'm sleeping dude",
    "Ask the FBI agent outside your house",
    "Why don't you tell me?",
    "A profound feeling of existential dread",
    "The square root of IDGAF.",
    "blue",
    "error. restart your computer to find the answer",
    "the answer is behind you",
    "0001010011101010001001010010101000101",
    "Don't worry about it.",
    "you don't need to know that",
    "You can't handle the answer",
    "just so you know, a pack of wild dogs are coming to you",
    "more cheese",
    "cheese",
    "even more cheese",
    "wouldn't you like to know",
    "why do you ask?",
    "who knows"
];

export const exitText = [
    "decrease me from here",
    "transfer my pixels away",
    "leave me alone from here",
    "delete me from this page",
    "be my ex calculator",
    "i want to look outside here",
    "uninstall me from here",
    "substract my pixels out",
    "calculate me out of here",
    "this page minus me please",
    "empty me from here",
    "this calculator minus me",
    "produce result of back button",
    "uncompute me from this screen",
    "release my cursor from here",
    "let me be the ghost of here",
    "make me never happened here"
]

